proc import file='../Raw_data/L1_ALFALFA_CUBES.xlsx' out=L1_ALFALFA_CUBES dbms=xlsx replace; run;
ods html close;
ods html;
Title "LAB 1 DAIRYONE RAW DATA WITHIN ALFALFA CUBES."; 
/* set nutrient concentrations to missing. */ 
DATA a01; 
SET L1_ALFALFA_CUBES;
IF DM = 0 THEN DM = '.';
IF CP = 0 THEN CP = '.'; 
IF NDF = 0 THEN NDF = '.'; 
IF Ash = 0 THEN Ash = '.'; 
IF Lignin = 0 THEN Lignin = '.'; 
IF TDN = 0 THEN TDN = '.'; 
IF DE = 0 THEN DE = '.'; 
IF ME = 0 THEN ME = '.'; 
IF NEM = 0 THEN NEM = '.'; 
IF NEG = 0 THEN NEG = '.'; 
IF Starch = 0 THEN Starch = '.'; 
IF Fat = 0 THEN Fat = '.'; 
IF ADF = 0 THEN ADF = '.'; 
IF RDP = 0 THEN RDP = '.'; 
IF RUP = 0 THEN RUP = '.'; 
IF Sol_Protein = 0 THEN Sol_Protein = '.'; 
IF ADIN = 0 THEN ADIN = '.'; 
IF Ca = 0 THEN Ca = '.'; 
IF P = 0 THEN P = '.'; 
IF Mg = 0 THEN Mg = '.'; 
IF K = 0 THEN K = '.'; 
IF NA = 0 THEN NA = '.'; 
IF Cl = 0 THEN Cl = '.'; 
IF S = 0 THEN S = '.'; 
IF Co = 0 THEN Co = '.'; 
IF Cu = 0 THEN Cu = '.'; 
IF Fe = 0 THEN Fe = '.'; 
IF Mn = 0 THEN Mn = '.'; 
IF Se = 0 THEN Se = '.'; 
IF Zn = 0 THEN Zn = '.'; 

RUN; 
PROC UNIVARIATE DATA=a01; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P Mg K NA Cl S Co Cu Fe Mn Se Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P Mg K NA Cl S Co Cu Fe Mn Se Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P;
RUN; 
proc sgplot data=a01;
  histogram  DM;
  density DM ;
  density DM / type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01;
  histogram  CP;
  density CP ;
  density CP / type=kernel;
  keylegend / location = inside position = topright; 
run;
/*remove extreme values based on output of 1% quantile*/
DATA a01a; 
SET a01; 
IF DM < 86.47 or DM > 95.7 THEN DM ='.';
IF ASH < 2.92 or ASH > 21.19 THEN ASH ='.';
IF TDN < 44.58 or TDN > 67.32 THEN TDN = '.'; 
IF DE < 2.03 or DE >3.12 THEN DE = '.'; 
IF ME < 1.6 or ME > 2.71 THEN ME = '.'; 
IF NEM < 0.66 or NEM >1.62 THEN NEM = '.'; 
IF NEG < 0.14 or NEG > 1.02 THEN NEG = '.'; 
IF Starch < 0 or STARCH > 5.37 THEN Starch = '.'; 
IF Fat < 0.5 or FAT > 4.81 THEN Fat = '.'; 
IF NDF < 23.92 or NDF > 67.42 THEN NDF = '.'; 
IF ADF < 20.53 or ADF > 50.47 THEN ADF = '.'; 
IF CP < 8.23 or CP > 27.9 THEN CP='.';
IF ADIN < 0.28 or ADIN > 2.36 THEN ADIN = '.'; 
IF Ca < 0.35 or Ca > 2.8 THEN Ca = '.'; 
IF P > 0.43 THEN P = '.'; 
IF Mg < 0.1 or Mg > 0.56 THEN Mg = '.'; 
IF NA < 0.11 or NA > 0.34 THEN NA = '.'; 
IF Cu > 18.42 THEN Cu = '.'; 
IF Fe < 99 or Fe > 3435.21 THEN Fe = '.'; 
IF Mn < 13 or Mn > 100.06 THEN Mn = '.'; 
IF Zn > 46.96 THEN Zn = '.'; 
RUN;
proc sgplot data=a01a;
  histogram  CP;
  density CP ;
  density CP/ type=kernel;
  keylegend / location = inside position = topright; 
run;

PROC univariate DATA=a01a; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P Mg K NA Cl S Co Cu Fe Mn Se Zn; 
RUN;
PROC corr DATA=a01a; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P Mg K NA Cl S Co Cu Fe Mn Se Zn; 
RUN;
PROC corr DATA=a01A; 
VAR DM Ash TDN DE ME NEM NEG Starch Fat NDF ADF Lignin CP RDP RUP Sol_Protein ADIN Ca P;
RUN;
