/*L1_OAT_HAY. */
proc import file='C:\Users\Huyen Tran\Documents\NANP\BeefNRC\L1.test\L1_OAT_HAY.XLSX' out=L1_OAT_HAY dbms=xlsx replace; run;
ods html close;
ods html;
Title "LAB 1 DAIRYONE REMOVE 3.5 SD WITHIN L1_OAT_HAY"; 
/* set nutrient concentrations to missing. */ 
DATA a01; 
SET L1_OAT_HAY;
IF DM = 0 THEN DM = '.';
IF CP = 0 THEN CP = '.'; 
IF NDF = 0 THEN NDF = '.'; 
IF Ash = 0 THEN Ash = '.'; 
IF Lignin = 0 THEN Lignin = '.'; 
IF TDN = 0 THEN TDN = '.'; 
IF DE = 0 THEN DE = '.'; 
IF ME = 0 THEN ME = '.'; 
IF NEM = 0 THEN NEM = '.'; 
IF NEG = 0 THEN NEG = '.'; 
IF Starch = 0 THEN Starch = '.'; 
IF Fat = 0 THEN Fat = '.'; 
IF ADF = 0 THEN ADF = '.'; 
IF RDP = 0 THEN RDP = '.'; 
IF RUP = 0 THEN RUP = '.'; 
IF Sol_Protein = 0 THEN Sol_Protein = '.'; 
IF ADIN = 0 THEN ADIN = '.'; 
IF Ca = 0 THEN Ca = '.'; 
IF P = 0 THEN P = '.'; 
IF Mg = 0 THEN Mg = '.'; 
IF K = 0 THEN K = '.'; 
IF NA = 0 THEN NA = '.'; 
IF Cl = 0 THEN Cl = '.'; 
IF S = 0 THEN S = '.'; 
IF Co = 0 THEN Co = '.'; 
IF Cu = 0 THEN Cu = '.'; 
IF Fe = 0 THEN Fe = '.'; 
IF Mn = 0 THEN Mn = '.'; 
IF Se = 0 THEN Se = '.'; 
IF Zn = 0 THEN Zn = '.'; 

RUN; 
PROC UNIVARIATE DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN; 
proc sgplot data=a01;
  histogram  DM;
  density DM ;
  density DM / type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01;
  histogram  CP;
  density CP ;
  density CP / type=kernel;
  keylegend / location = inside position = topright; 
run;

DATA a01a; 
SET a01; 
if DM < 84.88 or DM > 96.37 then DM ='.';
IF Ash > 15 THEN Ash = '.'; 
IF TDN < 44.84 or TDN > 75.07 THEN TDN = '.'; 
IF DE < 1.96 or DE > 3.28 THEN DE = '.'; 
IF ME < 1.53 or ME > 2.87 THEN ME = '.'; 
IF NEM < 0.64 or NEM > 1.77 THEN NEM = '.'; 
IF NEG < 0.12 or NEG > 1.15 THEN NEG = '.'; 
IF STARCH > 14.91 THEN Starch = '.'; 
IF FAT > 4.8 THEN FAT = '.'; 
IF NDF < 35.71 or NDF > 82.32 THEN NDF = '.';
IF ADF < 20.36 or ADF > 54.41 THEN ADF = '.'; 
IF LIGNIN > 10.07 THEN LIGNIN = '.'; 
IF CP > 19.99 THEN CP = '.'; 
IF RDP < 39.82 THEN RDP = '.'; 
IF RUP >  60.31 THEN RUP = '.'; 
IF SOL_PROTEIN < 18.33 or SOL_PROTEIN > 63.43 THEN SOL_PROTEIN = '.'; 
IF ADIN > 1.48 THEN ADIN = '.'; 
IF Ca > 0.87 THEN Ca = '.'; 
IF P > 0.42 THEN P = '.'; 
IF Mg > 0.32  THEN Mg = '.'; 
IF K > 3.97 THEN K = '.'; 
IF NA > 1.55 THEN NA = '.'; 
IF Cl > 2.74 THEN Cl = '.'; 
IF S > 0.32 THEN S = '.'; 
IF Cu > 32.72 THEN Cu = '.'; 
IF Fe > 1615.09 THEN Fe = '.'; 
IF Mn > 186.9 THEN Mn = '.'; 
IF Zn > 155.3 THEN Zn = '.'; 
RUN;


PROC univariate DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01A; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01a;
  histogram  DM;
  density DM ;
  density DM/ type=kernel;
  keylegend / location = inside position = topright; 
run;

DATA a01b; 
SET a01a;
if DM < 85.36 or DM > 95.94 then DM ='.';
IF Ash > 14.61 THEN Ash = '.'; 
IF TDN < 45.23 or TDN > 74.74 THEN TDN = '.'; 
IF DE < 1.98 or DE > 3.26 THEN DE = '.'; 
IF ME < 1.55 or ME > 2.84 THEN ME = '.'; 
IF NEM < 0.66 or NEM > 1.75 THEN NEM = '.'; 
IF NEG < 0.14 or NEG > 1.14 THEN NEG = '.'; 
IF STARCH > 13.52 THEN Starch = '.'; 
IF FAT > 4.36 THEN FAT = '.'; 
IF NDF < 36.28 THEN NDF = '.';
IF ADF < 20.78 or ADF > 53.91 THEN ADF = '.'; 
IF CP > 17.57 THEN CP = '.'; 
IF RDP < 40.05 THEN RDP = '.'; 
IF SOL_PROTEIN > 62.99 THEN SOL_PROTEIN = '.'; 
IF ADIN > 1.37 THEN ADIN = '.'; 
IF Ca < 0.08 or Ca > 0.76 THEN Ca = '.'; 
IF P < 0.09 or P > 0.41 THEN P = '.'; 
IF Mg > 0.3  THEN Mg = '.'; 
IF K > 3.78 THEN K = '.'; 
IF Na < 0.05 or NA > 1.38 THEN NA = '.'; 
IF Cl < 0.1 or Cl > 2.25 THEN Cl = '.'; 
IF S < 0.02 or S > 0.31 THEN S = '.'; 
IF Cu > 21.26 THEN Cu = '.'; 
IF Fe > 1122.74 THEN Fe = '.'; 
IF Mn > 168.41 THEN Mn = '.'; 
IF Zn > 75.89 THEN Zn = '.'; 
RUN;
PROC univariate DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01B;
  histogram  DM;
  density DM ;
  density DM/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  ASH;
  density ASH ;
  density ASH/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  ADF;
  density ADF ;
  density ADF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  NDF;
  density NDF ;
  density NDF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  cp;
  density cp ;
  density cp/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  starch;
  density starch ;
  density starch/ type=kernel;
  keylegend / location = inside position = topright; 
run;

