/*L1_CORN_SILAGE. */
proc import file='C:\Users\Huyen Tran\Documents\NANP\BeefNRC\L1.test\L1_CORN_SILAGE.XLSX' out=L1_CORN_SILAGE dbms=xlsx replace; run;
ods html close;
ods html;
Title "LAB 1 DAIRYONE RAW DATA WITHIN L1_CORN_SILAGE"; 
/* set nutrient concentrations to missing. */ 
DATA a01; 
SET L1_CORN_SILAGE;
IF DM = 0 THEN DM = '.';
IF CP = 0 THEN CP = '.'; 
IF NDF = 0 THEN NDF = '.'; 
IF Ash = 0 THEN Ash = '.'; 
IF Lignin = 0 THEN Lignin = '.'; 
IF TDN = 0 THEN TDN = '.'; 
IF DE = 0 THEN DE = '.'; 
IF ME = 0 THEN ME = '.'; 
IF NEM = 0 THEN NEM = '.'; 
IF NEG = 0 THEN NEG = '.'; 
IF Starch = 0 THEN Starch = '.'; 
IF Fat = 0 THEN Fat = '.'; 
IF ADF = 0 THEN ADF = '.'; 
IF RDP = 0 THEN RDP = '.'; 
IF RUP = 0 THEN RUP = '.'; 
IF Sol_Protein = 0 THEN Sol_Protein = '.'; 
IF ADIN = 0 THEN ADIN = '.'; 
IF Ca = 0 THEN Ca = '.'; 
IF P = 0 THEN P = '.'; 
IF Mg = 0 THEN Mg = '.'; 
IF K = 0 THEN K = '.'; 
IF NA = 0 THEN NA = '.'; 
IF Cl = 0 THEN Cl = '.'; 
IF S = 0 THEN S = '.'; 
IF Co = 0 THEN Co = '.'; 
IF Cu = 0 THEN Cu = '.'; 
IF Fe = 0 THEN Fe = '.'; 
IF Mn = 0 THEN Mn = '.'; 
IF Se = 0 THEN Se = '.'; 
IF Zn = 0 THEN Zn = '.'; 
RUN; 
PROC UNIVARIATE DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN; 
proc sgplot data=a01;
  histogram  DM;
  density DM ;
  density DM / type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01;
  histogram  CP;
  density CP ;
  density CP / type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01;
  histogram  ash;
  density ash ;
  density ash / type=kernel;
  keylegend / location = inside position = topright; 
run;

/*remove 3.5 SD FROM THE MEANS*/
/*For Silage, remove DM >70*/
DATA a01a; 
SET a01; 
IF DM > 70 THEN DM ='.';
IF Ash > 8.64 THEN Ash = '.'; 
IF TDN < 58.58 or TDN > 77.01 THEN TDN = '.'; 
IF DE < 2.57 or DE > 3.33 THEN DE = '.'; 
IF ME < 2.14 or ME > 2.91 THEN ME = '.'; 
IF NEM < 1.15 or NEM > 2.14 THEN NEM = '.'; 
IF NEG < 0.59 or NEG > 1.48 THEN NEG = '.'; 
IF STARCH < 6.93 or STARCH > 57.96 THEN STARCH = '.'; 
IF FAT < 1.47 or FAT > 5.06 THEN FAT = '.';
IF NDF < 22.89 or NDF > 63.32 THEN NDF = '.'; 
IF ADF< 11.49 or ADF > 39.48 THEN ADF = '.'; 
IF LIGNIN < 0.90 or LIGNIN > 5.47 THEN LIGNIN = '.'; 
IF CP < 4.57 or CP > 11.93 THEN CP = '.';
IF RDP < 49.19 THEN RDP = '.';
IF RUP > 50.65 THEN RUP = '.';
IF Sol_PROTEIN < 20.93 or Sol_PROTEIN > 90.66 THEN SOL_PROTEIN = '.';
IF ADIN < 0.08 or ADIN > 1.1 THEN ADIN= '.';
IF Ca < 0 or Ca > 0.56 THEN Ca = '.';
IF P < 0.11 or P > 0.36 THEN P = '.';
IF Mg < 0.04 or Mg > 0.30 THEN Mg = '.';
IF K < 0.15 or K > 1.99 THEN K = '.';
IF NA > 0.29 THEN NA = '.';
IF Cl > 0.71 THEN Cl = '.';
IF S > 0.17 THEN S = '.';
IF Co > 4.5 THEN Co = '.';
IF Cu > 19.1 THEN Cu = '.';
IF Fe > 1266.42 THEN Fe = '.';
IF Mn > 98.92 THEN Mn = '.';
IF Zn > 774.31 THEN Zn = '.'; 
RUN;
PROC univariate DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01A; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01a;
  histogram  dm;
  density dm ;  density dm/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01a;
  histogram  ASH;
  density ASH ;
  density ASH/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01a;
  histogram  CP;
  density CP ;
  density CP/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01A;
  histogram  STARCH;
  density STARCH ;
  density STARCH/ type=kernel;
  keylegend / location = inside position = topright; 
run;
DATA a01b; 
SET a01A;
IF DM < 12.95 or DM > 53.09 THEN DM ='.';
IF Ash < 0.36 or Ash > 8.12 THEN Ash = '.'; 
IF TDN < 59.42 or TDN > 76.33 THEN TDN = '.'; 
IF DE < 2.60 or DE > 3.3 THEN DE = '.'; 
IF ME < 2.18 or ME > 2.89 THEN ME = '.'; 
IF NEM < 1.17 or NEM > 2.13 THEN NEM = '.'; 
IF NEG < 0.61 or NEG > 1.46 THEN NEG = '.'; 
IF STARCH < 8.28 or STARCH > 56.95 THEN STARCH = '.'; 
IF FAT < 1.55 or FAT > 4.97 THEN FAT = '.';
IF NDF < 24.04 or NDF > 61.86 THEN NDF = '.'; 
IF ADF < 12.13 or ADF > 38.66 THEN ADF = '.'; 
IF LIGNIN < 1.04 or LIGNIN > 5.3 THEN LIGNIN = '.'; 
IF CP < 4.84 or CP > 11.60 THEN CP = '.';
IF RDP < 50.91 THEN RDP = '.';
IF RUP > 48.99 THEN RUP = '.';
IF Sol_PROTEIN < 21.61 THEN SOL_PROTEIN = '.';
IF ADIN < 0.11 or ADIN > 1.07 THEN ADIN= '.';
IF Ca < 0.02 or Ca > 0.45 THEN Ca = '.';
IF P < 0.12 or P > 0.35 THEN P = '.';
IF Mg < 0.05 or Mg > 0.28 THEN Mg = '.';
IF K < 0.22 or K > 1.91 THEN K = '.';
IF NA > 0.09 THEN NA = '.';
IF Cl > 0.65 THEN Cl = '.';
IF S > 0.16 THEN S = '.';
IF Co > 2.63 THEN Co = '.';
IF Cu > 13.42 THEN Cu = '.';
IF Fe > 760.07 THEN Fe = '.';
IF Mn > 83.25 THEN Mn = '.';
IF Zn > 126.94 THEN Zn = '.'; 
RUN;
PROC univariate DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01B;
  histogram  DM;
  density DM ;
  density DM/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  ADF;
  density ADF ;
  density ADF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  NDF;
  density NDF ;
  density NDF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  cp;
  density cp ;
  density cp/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  STARCH;
  density STARCH ;
  density STARCH/ type=kernel;
  keylegend / location = inside position = topright; 
run;
PROC univariate DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
