/*L1_SOYBEAN_MEAL_Dry. */
proc import file='C:\Users\Huyen Tran\Documents\NANP\BeefNRC\L1.test\L1_SOYBEAN_MEAL_Dry.XLSX' out=L1_SOYBEAN_MEAL_Dry dbms=xlsx replace; run;
ods html close;
ods html;
Title "LAB 1 DAIRYONE REMOVE 3.5 SD WITHIN L1_SOYBEAN_MEAL_Dry"; 
/* set nutrient concentrations to missing. */ 
DATA a01; 
SET L1_SOYBEAN_MEAL_Dry;
IF DM = 0 THEN DM = '.';
IF CP = 0 THEN CP = '.'; 
IF NDF = 0 THEN NDF = '.'; 
IF Ash = 0 THEN Ash = '.'; 
IF Lignin = 0 THEN Lignin = '.'; 
IF TDN = 0 THEN TDN = '.'; 
IF DE = 0 THEN DE = '.'; 
IF ME = 0 THEN ME = '.'; 
IF NEM = 0 THEN NEM = '.'; 
IF NEG = 0 THEN NEG = '.'; 
IF Starch = 0 THEN Starch = '.'; 
IF Fat = 0 THEN Fat = '.'; 
IF ADF = 0 THEN ADF = '.'; 
IF RDP = 0 THEN RDP = '.'; 
IF RUP = 0 THEN RUP = '.'; 
IF Sol_Protein = 0 THEN Sol_Protein = '.'; 
IF ADIN = 0 THEN ADIN = '.'; 
IF Ca = 0 THEN Ca = '.'; 
IF P = 0 THEN P = '.'; 
IF Mg = 0 THEN Mg = '.'; 
IF K = 0 THEN K = '.'; 
IF NA = 0 THEN NA = '.'; 
IF Cl = 0 THEN Cl = '.'; 
IF S = 0 THEN S = '.'; 
IF Co = 0 THEN Co = '.'; 
IF Cu = 0 THEN Cu = '.'; 
IF Fe = 0 THEN Fe = '.'; 
IF Mn = 0 THEN Mn = '.'; 
IF Se = 0 THEN Se = '.'; 
IF Zn = 0 THEN Zn = '.'; 

RUN; 
PROC UNIVARIATE DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN; 
PROC CORR DATA=a01; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN; 
proc sgplot data=a01;
  histogram  DM;
  density DM ;
  density DM / type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01;
  histogram  CP;
  density CP ;
  density CP / type=kernel;
  keylegend / location = inside position = topright; 
run;

DATA a01a; 
SET a01; 
if DM < 82.53 or DM > 98.29 then DM ='.';
IF Ash < 2.8 or Ash > 11.58 THEN Ash = '.'; 
IF TDN < 65.67 or TDN > 94.78 THEN TDN = '.'; 
IF DE < 3.44 or DE > 4.71 THEN DE = '.'; 
IF ME < 3.0 or ME > 4.34 THEN ME = '.'; 
IF NEM < 1.36 or NEM > 2.53 THEN NEM = '.'; 
IF NEG < 0.8 or NEG > 1.79 THEN NEG = '.'; 
IF STARCH > 6.23 THEN Starch = '.'; 
IF FAT > 21.97 THEN FAT = '.'; 
IF NDF > 34.59 THEN NDF = '.';
IF ADF > 20.07 THEN ADF = '.'; 
IF LIGNIN > 4.35 THEN LIGNIN = '.'; 
IF CP > 67.62 THEN CP = '.'; 
IF RDP < 20.38 THEN RDP = '.'; 
IF RUP > 79.49 THEN RUP = '.'; 
IF SOL_PROTEIN > 55.89 THEN SOL_PROTEIN = '.'; 
IF ADIN > 6.75 THEN ADIN = '.'; 
IF Ca > 1.32 THEN Ca = '.'; 
IF P > 1.47 THEN P = '.'; 
IF Mg > 0.54  THEN Mg = '.'; 
IF K < 0.99 THEN K = '.'; 
IF NA > 0.54 THEN NA = '.'; 
IF Cl > 4.7 THEN Cl = '.'; 
IF S > 0.57 THEN S = '.'; 
IF Cu > 26.92 THEN Cu = '.'; 
IF Fe > 1034.9 THEN Fe = '.'; 
IF Mn > 79.39 THEN Mn = '.'; 
IF Zn > 140.88 THEN Zn = '.'; 
RUN;


PROC univariate DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01a; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01A; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01a;
  histogram  DM;
  density DM ;
  density DM/ type=kernel;
  keylegend / location = inside position = topright; 
run;

DATA a01b; 
SET a01a;
if DM < 82.87 or DM > 97.85then DM ='.';
IF Ash < 3.78 THEN Ash = '.'; 
IF TDN < 68.86 or TDN > 91.01 THEN TDN = '.'; 
IF DE < 3.57 or DE > 4.57 THEN DE = '.'; 
IF ME < 3.14 or ME > 4.19 THEN ME = '.'; 
IF NEM < 1.49 or NEM > 2.37 THEN NEM = '.'; 
IF NEG < 0.91 or NEG > 1.66 THEN NEG = '.'; 
IF STARCH > 4.86 THEN Starch = '.'; 
IF FAT > 18.61 THEN FAT = '.'; 
IF NDF > 30.39 THEN NDF = '.';
IF ADF > 17.05 THEN ADF = '.'; 
IF LIGNIN > 3.44 THEN LIGNIN = '.'; 
IF CP < 35.02 THEN CP = '.'; 
IF SOL_PROTEIN >51.8 THEN SOL_PROTEIN = '.'; 
IF ADIN > 5.56 THEN ADIN = '.'; 
IF Ca > 0.81 THEN Ca = '.'; 
IF P < 0.37 THEN P = '.'; 
IF Mg < 0.16 or Mg > 0.46  THEN Mg = '.'; 
IF K < 1.22 or  K > 3.33 THEN K = '.'; 
IF NA > 0.21 THEN NA = '.'; 
IF Cl > 2.49 THEN Cl = '.'; 
IF S > 0.56 THEN S = '.'; 
IF Cu < 4.49 THEN Cu = '.'; 
IF Fe > 654.18 THEN Fe = '.'; 
IF Mn > 74.6 THEN Mn = '.'; 
IF Zn > 92.92 THEN Zn = '.';
RUN;
PROC univariate DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P	Mg 	K	NA	Cl 	S 	Co 	Cu 	Fe 	Mn 	Se 	Zn; 
RUN;
PROC corr DATA=a01B; 
VAR DM	Ash	TDN	DE	ME	NEM	NEG	Starch	Fat	NDF	ADF	Lignin	CP	RDP	RUP	Sol_Protein	ADIN Ca	P;
RUN;
proc sgplot data=a01B;
  histogram  DM;
  density DM ;
  density DM/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  ASH;
  density ASH ;
  density ASH/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  ADF;
  density ADF ;
  density ADF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  NDF;
  density NDF ;
  density NDF/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  cp;
  density cp ;
  density cp/ type=kernel;
  keylegend / location = inside position = topright; 
run;
proc sgplot data=a01B;
  histogram  starch;
  density starch ;
  density starch/ type=kernel;
  keylegend / location = inside position = topright; 
run;

